# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createNet.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Create_new_net(object):
    def setupUi(self, Create_new_net):
        Create_new_net.setObjectName("Create_new_net")
        Create_new_net.resize(1009, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Create_new_net.sizePolicy().hasHeightForWidth())
        Create_new_net.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Create_new_net.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Create_new_net)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(Create_new_net)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Create_new_net)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openBtn = QtWidgets.QPushButton(Create_new_net)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout.addWidget(self.openBtn)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Create_new_net)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(Create_new_net)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(Create_new_net)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tableWidget_2 = QtWidgets.QTableWidget(Create_new_net)
        self.tableWidget_2.setAutoFillBackground(False)
        self.tableWidget_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        self.verticalLayout.addWidget(self.tableWidget_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(Create_new_net)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)

        self.retranslateUi(Create_new_net)
        QtCore.QMetaObject.connectSlotsByName(Create_new_net)

    def retranslateUi(self, Create_new_net):
        _translate = QtCore.QCoreApplication.translate
        Create_new_net.setWindowTitle(_translate("Create_new_net", "Create new network"))
        self.lineEdit.setText(_translate("Create_new_net", "Имя сети"))
        self.pushButton.setText(_translate("Create_new_net", "Сохранить"))
        self.openBtn.setText(_translate("Create_new_net", "Открыть сеть из файла"))
        self.label_2.setText(_translate("Create_new_net", "Количество узлов"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Create_new_net", "ГЭС"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Create_new_net", "ГАЭС"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Create_new_net", "АЭС"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Create_new_net", "Газ"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Create_new_net", "Уголь"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Create_new_net", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Create_new_net", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Create_new_net", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Create_new_net", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Create_new_net", "5"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Create_new_net", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Create_new_net", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Create_new_net", "3"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Create_new_net", "4"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Create_new_net", "5"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
